import { createClient } from '@/utils/supabase/client';
export type MenuItem = { id: string; name: string; description: string; price: number; emoji: string };
export type Guest = { id: string; display_name: string; is_host: boolean };
export type CartItem = { id: string; guest_id: string; menu_item_id: string; quantity: number };
export type DemoTable = { id: string; display_name: string; restaurant_id: string; table_code: string };
export type DemoSession = { id: string; status: 'OPEN' | 'PLACED' | 'PREPARING' | 'READY' | 'COMPLETE'; table_id: string; created_at: string };
const db = createClient();
export async function loadTable(tableCode: string) { const { data: table, error } = await db.from('demo_tables').select('id, display_name, restaurant_id, table_code').eq('table_code', tableCode).single(); if (error || !table) throw new Error('This table link is not active.'); const [{ data: restaurant }, { data: menu }] = await Promise.all([db.from('demo_restaurants').select('name').eq('id', table.restaurant_id).single(), db.from('demo_menu_items').select('id, name, description, price, emoji').eq('restaurant_id', table.restaurant_id).eq('is_available', true).order('position')]); return { table: table as DemoTable, restaurant: restaurant?.name ?? 'Your restaurant', menu: (menu ?? []) as MenuItem[] }; }
export async function findOpenSession(tableId: string) { const { data, error } = await db.from('demo_table_sessions').select('id, status, table_id, created_at').eq('table_id', tableId).eq('status', 'OPEN').order('created_at', { ascending: false }).limit(1).maybeSingle(); if (error) throw error; return data as DemoSession | null; }
export async function joinTable(tableId: string, name: string, phone?: string) { let session = await findOpenSession(tableId); let isHost = false; if (!session) { const { data, error } = await db.from('demo_table_sessions').insert({ table_id: tableId }).select('id, status, table_id, created_at').single(); if (error || !data) throw new Error('Someone else may have just opened this table. Please try again.'); session = data as DemoSession; isHost = true; } const { data: guest, error: guestError } = await db.from('demo_session_guests').insert({ session_id: session.id, display_name: name, is_host: isHost }).select('id, display_name, is_host').single(); if (guestError || !guest) throw new Error('Could not join the table. Please try again.'); if (isHost && phone) { const { error: phoneError } = await db.from('demo_host_contacts').insert({ session_id: session.id, phone }); if (phoneError) throw new Error('Your name was added, but we could not save the billing contact.'); } return { session, guest: guest as Guest }; }
export async function loadSession(sessionId: string) { const [{ data: session }, { data: guests }, { data: cart }] = await Promise.all([db.from('demo_table_sessions').select('id, status, table_id, created_at').eq('id', sessionId).single(), db.from('demo_session_guests').select('id, display_name, is_host').eq('session_id', sessionId).order('joined_at'), db.from('demo_cart_items').select('id, guest_id, menu_item_id, quantity').eq('session_id', sessionId).order('created_at')]); return { session: session as DemoSession | null, guests: (guests ?? []) as Guest[], cart: (cart ?? []) as CartItem[] }; }
export async function addToCart(sessionId: string, guestId: string, menuItemId: string) { const { data: existing } = await db.from('demo_cart_items').select('id, quantity').eq('guest_id', guestId).eq('menu_item_id', menuItemId).maybeSingle(); return existing ? db.from('demo_cart_items').update({ quantity: existing.quantity + 1 }).eq('id', existing.id) : db.from('demo_cart_items').insert({ session_id: sessionId, guest_id: guestId, menu_item_id: menuItemId }); }
export async function placeOrder(sessionId: string) { return db.from('demo_table_sessions').update({ status: 'PLACED' }).eq('id', sessionId).eq('status', 'OPEN'); }
export { db };
