"use client";
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { addToCart, findOpenSession, joinTable, loadSession, loadTable, placeOrder, type CartItem, type DemoSession, type Guest, type MenuItem } from '@/lib/demo';
const initials = (name: string) => name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase();
export default function Customer() {
  const [code, setCode] = useState('SAGE-12'); const [restaurant, setRestaurant] = useState(''); const [tableName, setTableName] = useState(''); const [tableId, setTableId] = useState(''); const [menu, setMenu] = useState<MenuItem[]>([]); const [session, setSession] = useState<DemoSession | null>(null); const [guest, setGuest] = useState<Guest | null>(null); const [guests, setGuests] = useState<Guest[]>([]); const [cart, setCart] = useState<CartItem[]>([]); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [needsPhone, setNeedsPhone] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [adding, setAdding] = useState<string | null>(null);
  useEffect(() => { const next = new URLSearchParams(window.location.search).get('table')?.toUpperCase() ?? 'SAGE-12'; setCode(next); loadTable(next).then(async data => { setRestaurant(data.restaurant); setTableName(data.table.display_name); setTableId(data.table.id); setMenu(data.menu); setNeedsPhone(!(await findOpenSession(data.table.id))); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  const refresh = async () => { if (!session) return; const data = await loadSession(session.id); setSession(data.session); setGuests(data.guests); setCart(data.cart); };
  useEffect(() => { if (!session) return; refresh(); const id = window.setInterval(refresh, 3000); return () => window.clearInterval(id); }, [session?.id]);
  const join = async () => { if (!name.trim()) return setError('Enter your name to join the table.'); if (needsPhone && phone.trim().length < 7) return setError('The first guest adds a billing contact number.'); try { const joined = await joinTable(tableId, name.trim(), needsPhone ? phone.trim() : undefined); sessionStorage.setItem(`tablesync-demo-${code}`, JSON.stringify({ sessionId: joined.session.id, guest: joined.guest })); setSession(joined.session); setGuest(joined.guest); setNeedsPhone(false); } catch (e) { setError(e instanceof Error ? e.message : 'Could not join the table.'); } };
  useEffect(() => { if (!tableId || guest) return; const saved = sessionStorage.getItem(`tablesync-demo-${code}`); if (!saved) return; try { const parsed = JSON.parse(saved); setGuest(parsed.guest); loadSession(parsed.sessionId).then(data => { if (data.session?.status === 'OPEN') setSession(data.session); else sessionStorage.removeItem(`tablesync-demo-${code}`); }); } catch { sessionStorage.removeItem(`tablesync-demo-${code}`); } }, [tableId, code, guest]);
  const add = async (id: string) => { if (!session || !guest) return; setAdding(id); const { error: addError } = await addToCart(session.id, guest.id, id); if (addError) setError('Could not add that dish.'); await refresh(); setAdding(null); };
  const myTotal = useMemo(() => cart.filter(item => item.guest_id === guest?.id).reduce((sum, item) => sum + (menu.find(dish => dish.id === item.menu_item_id)?.price ?? 0) * item.quantity, 0), [cart, guest, menu]);
  const total = useMemo(() => cart.reduce((sum, item) => sum + (menu.find(dish => dish.id === item.menu_item_id)?.price ?? 0) * item.quantity, 0), [cart, menu]);
  if (loading) return <main className="arrival-page"><p>Loading your table…</p></main>;
  if (!guest || !session) return <main className="arrival-page"><Link className="brand" href="/">table<i>sync</i></Link><section className="arrival-card"><p className="kicker">You&apos;ve arrived</p><h1>{restaurant || 'Your table'}</h1><p className="arrival-table">{tableName} <span>·</span> Shared order</p><div className="arrival-art"><span>✦</span><i>Tonight&apos;s table is waiting</i></div><label htmlFor="guest-name">What should we call you?</label><input id="guest-name" value={name} onChange={e => setName(e.target.value)} placeholder="Your first name" autoFocus />{needsPhone && <><label htmlFor="phone">Billing contact number</label><input id="phone" value={phone} onChange={e => setPhone(e.target.value)} inputMode="tel" placeholder="Only the first guest needs this" /><p className="quiet-note">Used only for this table&apos;s bill; other guests just add their names.</p></>}<button className="primary-button full" onClick={join}>Join the table <span>→</span></button>{error && <p className="form-error">{error}</p>}</section></main>;
  const placed = session.status !== 'OPEN';
  return <main className="diner-page"><header className="diner-header"><Link className="brand" href="/">table<i>sync</i></Link><div className="table-live"><span />{placed ? 'Order sent' : 'Live table'}</div></header>{error && <p className="inline-error">{error}</p>}<section className="diner-hero"><div><p className="kicker light">{restaurant} <span>·</span> {tableName}</p><h1>Good evening, {guest.display_name}.</h1><p>{placed ? 'Your table order is with the kitchen.' : 'Everyone can add dishes at their own pace.'}</p></div><div className="guest-stack">{guests.slice(0, 4).map((entry, i) => <span className={`guest guest-${i}`} title={entry.display_name} key={entry.id}>{initials(entry.display_name)}</span>)}<small>{guests.length} at table</small></div></section><section className="menu-section"><div className="section-heading"><div><p className="kicker">Today&apos;s menu</p><h2>Order at your own pace.</h2></div><span className="menu-note">{placed ? 'Order closed' : 'Tap + to add yours'}</span></div><div className="menu-grid">{menu.map(item => <article className="dish-card" key={item.id}><div className="dish-art">{item.emoji}</div><div className="dish-copy"><h3>{item.name}</h3><p>{item.description}</p></div><strong>₹{item.price}</strong><button className="round-add" disabled={placed || adding === item.id} aria-label={`Add ${item.name}`} onClick={() => add(item.id)}>{adding === item.id ? '…' : '+'}</button></article>)}</div></section><div className="cart-bar"><div><span>{cart.reduce((n, item) => n + item.quantity, 0)} items in the shared order</span><strong>{myTotal ? `Your dishes · ₹${myTotal}` : `Table total · ₹${total}`}</strong></div><button disabled={!cart.length || placed} onClick={async () => { const { error: placeError } = await placeOrder(session.id); if (placeError) setError('Could not send this order.'); await refresh(); }}>{placed ? 'Sent to kitchen' : 'Place table order'} <span>→</span></button></div><p className="quiet-note center">Demo ordering only — payment is not collected in this hosted preview.</p></main>;
}
