"use client";
import { useEffect, useMemo, useState } from "react";

type MenuItem = { id:string; name:string; description:string; price:number; emoji:string };
type Participant = { id:string; name:string };
type CartItem = { id:string; menuItemId:string; ownerId:string; name:string; price:number; emoji:string; quantity:number };
type Session = { tableCode:string; restaurant:string; tableName:string; participants:Participant[]; items:CartItem[]; menu:MenuItem[]; collaborative:boolean; subtotal:number };
type PaymentSaga = { id:string; status:string; totalAmount:number; platformFee:number; simulated:boolean; intents:{intentId:string;participantId:string;amount:number;status:string}[] };
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080";

export default function Customer(){
  const [session,setSession]=useState<Session|null>(null); const [error,setError]=useState(""); const [adding,setAdding]=useState<string|null>(null); const [checkingOut,setCheckingOut]=useState(false); const [payment,setPayment]=useState<PaymentSaga|null>(null);
  const participant=useMemo(()=>({id:typeof window==='undefined'?"maya":sessionStorage.getItem("tablesync-participant")??crypto.randomUUID(),name:"Maya"}),[]);
  useEffect(()=>{sessionStorage.setItem("tablesync-participant",participant.id); const join=async()=>{try{const response=await fetch(`${api}/v1/table-sessions/join`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tableCode:"SAGE-12",participant})});if(!response.ok)throw new Error("Could not join Table 12");setSession(await response.json());const socket=new WebSocket(`${api.replace("http","ws")}/v1/table-sessions/SAGE-12/live`);socket.onmessage=event=>setSession(JSON.parse(event.data).session);return()=>socket.close()}catch{setError("The local TableSync API is offline. Start it with npm run dev:api.")}};let cleanup:undefined|(()=>void);join().then(value=>cleanup=value);return()=>cleanup?.()},[participant]);
  const add=async(menuItemId:string)=>{setAdding(menuItemId);try{const response=await fetch(`${api}/v1/table-sessions/SAGE-12/cart-items`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({participantId:participant.id,menuItemId})});if(!response.ok)throw new Error();setSession(await response.json())}catch{setError("Could not add that item. Check the local API.")}finally{setAdding(null)}};
  const checkout=async(outcome:"success"|"failure"|"timeout")=>{setCheckingOut(true);setError("");try{const response=await fetch(`${api}/v1/table-sessions/SAGE-12/checkout`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({idempotencyKey:crypto.randomUUID(),outcomes:{[participant.id]:outcome}})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Checkout could not start");setPayment(body.payment)}catch(error){setError(error instanceof Error?error.message:"Checkout could not start")}finally{setCheckingOut(false)}};
  const cartCount=session?.items.reduce((sum,item)=>sum+item.quantity,0)??0;
  return <main className="app"><header><div className="brand">table<i>sync</i></div><span className="pill">{session?"Live table":"Connecting…"}</span></header>{error&&<p className="card" style={{color:'#a04429',fontSize:13}}>{error}</p>}<section className="table-card"><div className="eyebrow" style={{color:'#bcbfba'}}>{session?.restaurant??"Juniper House"} · {session?.tableName??"Table 12"}</div><h2 style={{margin:'6px 0'}}>Good evening, Maya</h2><p>{session?.collaborative?"Your table is ordering together. Changes are live.":"You’re ordering on your own — collaboration begins when another guest joins."}</p><div className="participants">{session?.participants.map((guest,index)=><div className="avatar" title={guest.name} style={index===1?{background:'#7d9fc6'}:index===2?{background:'#d59b64'}:{}} key={guest.id}>{guest.name[0]}</div>)}<span style={{fontSize:11,color:'#bcbfba',marginLeft:5}}>{session?.participants.length??0} at table</span></div></section><div className="eyebrow">Today’s menu</div><h2 className="section-title">Small plates & favourites</h2><section className="menu">{session?.menu.map(item=><div className="menu-item" key={item.id}><div className="food">{item.emoji}</div><div><strong>{item.name}</strong><small>{item.description}</small></div><div className="price">₹{item.price}</div><button className="add" disabled={adding===item.id} aria-label={'Add '+item.name} onClick={()=>add(item.id)}>{adding===item.id?'…':'+'}</button></div>)}</section><section className="checkout"><div>{cartCount?`${cartCount} item${cartCount>1?'s':''} in your shared cart`:'Start with something good'}</div><span>{session?`₹${session.subtotal}`:'—'}</span>{cartCount>0&&<><button className="checkout" disabled={checkingOut} onClick={()=>checkout('success')}>{checkingOut?'Starting simulated payment…':`Simulated UPI · Pay ₹${session?.subtotal}`}</button><div style={{display:'flex',gap:8,marginTop:8}}><button className="add" disabled={checkingOut} onClick={()=>checkout('failure')}>Simulate failure</button><button className="add" disabled={checkingOut} onClick={()=>checkout('timeout')}>Simulate timeout</button></div><small style={{display:'block',marginTop:8,opacity:.7}}>Test-only payment simulation. No money moves.</small></>}{payment&&<p style={{fontSize:13,lineHeight:1.5}}><strong>Simulated Saga {payment.status}</strong><br/>₹{payment.totalAmount} items · ₹{payment.platformFee} platform fee · {payment.intents.map(intent=>intent.status).join(', ')}</p>}</section></main>;
}
