import Fastify from 'fastify';
import amqp from 'amqplib';
import { randomUUID } from 'node:crypto';
import { Pool } from 'pg';
const database = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgresql://tablesync:tablesync@localhost:5432/tablesync' });
const sessionUrl = process.env.SESSION_SERVICE_URL ?? 'http://localhost:8081';
const menu = [{id:'dumplings',name:'Crispy corn dumplings',price:260,emoji:'🥟'},{id:'paneer',name:'Smoked butter paneer',price:340,emoji:'🍛'},{id:'noodles',name:'Chilli garlic noodles',price:280,emoji:'🍜'},{id:'milk-cake',name:'Saffron milk cake',price:190,emoji:'🍮'}];
let broker;
async function cartFor(sessionId) { const found = await database.query('SELECT id FROM carts WHERE session_id=$1',[sessionId]); if(found.rowCount)return found.rows[0];const cart={id:randomUUID()};await database.query('INSERT INTO carts (id,session_id) VALUES ($1,$2)',[cart.id,sessionId]);return cart; }
async function publish(type,data){if(broker)broker.publish('tablesync.events',type,Buffer.from(JSON.stringify({id:randomUUID(),version:1,occurredAt:new Date().toISOString(),correlationId:randomUUID(),type,data})),{persistent:true});}
export function buildApp(){const app=Fastify({logger:true});app.get('/health',async()=>{await database.query('SELECT 1');return{service:'order',status:'ok',rabbitmq:Boolean(broker)}});app.get('/v1/carts/:sessionId',async request=>{const cart=await cartFor(request.params.sessionId);const items=await database.query('SELECT id,menu_item_id AS "menuItemId",owner_id AS "ownerId",item_name AS name,unit_price AS price,emoji,quantity FROM cart_items WHERE cart_id=$1 ORDER BY created_at',[cart.id]);return{...cart,sessionId:request.params.sessionId,items:items.rows,subtotal:items.rows.reduce((total,item)=>total+item.price*item.quantity,0)}});app.post('/v1/carts/:sessionId/items',async(request,reply)=>{const{participantId,menuItemId}=request.body??{};const item=menu.find(entry=>entry.id===menuItemId);if(!participantId||!item)return reply.code(400).send({error:'participantId and valid menuItemId are required'});let session;try{const response=await fetch(`${sessionUrl}/v1/sessions/id/${request.params.sessionId}`);if(!response.ok)throw new Error();session=await response.json()}catch{return reply.code(503).send({error:'session service unavailable'})}if(!session.participants.some(participant=>participant.id===participantId))return reply.code(403).send({error:'participant is not part of this table session'});const cart=await cartFor(request.params.sessionId);await database.query('INSERT INTO cart_items (id,cart_id,menu_item_id,owner_id,item_name,unit_price,emoji,quantity) VALUES ($1,$2,$3,$4,$5,$6,$7,1) ON CONFLICT (cart_id,menu_item_id,owner_id) DO UPDATE SET quantity=cart_items.quantity+1',[randomUUID(),cart.id,item.id,participantId,item.name,item.price,item.emoji]);await publish('cart.item_added.v1',{sessionId:request.params.sessionId,item:{menuItemId,ownerId:participantId}});return app.inject({method:'GET',url:`/v1/carts/${request.params.sessionId}`}).then(response=>response.json())});return app;}
async function start(){await database.query('SELECT 1');const connection=await amqp.connect(process.env.RABBITMQ_URL??'amqp://guest:guest@localhost:5672');broker=await connection.createChannel();await broker.assertExchange('tablesync.events','topic',{durable:true});await broker.assertQueue('tablesync.audit',{durable:true});await broker.bindQueue('tablesync.audit','tablesync.events','#');const app=buildApp();await app.listen({port:Number(process.env.PORT??8082),host:'0.0.0.0'});}if(process.argv[1]?.endsWith('server.js'))start();
